### ISSUE TITLE
Garbage collection fails sometimes for kubeapps up

### ISSUE THREAD

**Issue by arapulido** [kubeapps/installer#21]
This might be a bug in Kubecfg

Sometimes, when doing kubeapps up you get the following error:

```
INFO[0000] Updating namespaces kubeapps
INFO[0000]  Creating non-existent namespaces kubeapps
INFO[0000] Updating namespaces kubeless
INFO[0004] Garbage collecting deployments kube-system.sealed-secrets-controller (extensions/v1beta1)
INFO[0004] Garbage collecting deployments kube-system.tiller-deploy (extensions/v1beta1)
INFO[0006] Garbage collecting deployments kube-system.sealed-secrets-controller (apps/v1beta1)
INFO[0006] Garbage collecting deployments kube-system.tiller-deploy (apps/v1beta1)
INFO[0006] Garbage collecting deployments kube-system.sealed-secrets-controller (apps/v1beta2)
INFO[0007] Garbage collecting deployments kube-system.tiller-deploy (apps/v1beta2)
INFO[0008] Garbage collecting clusterrolebindings kubeless-controller-deployer (rbac.authorization.k8s.io/v1)
INFO[0008] Garbage collecting clusterrolebindings sealed-secrets-controller (rbac.authorization.k8s.io/v1)
INFO[0009] Garbage collecting clusterroles kubeless-controller-deployer (rbac.authorization.k8s.io/v1)
INFO[0009] Garbage collecting clusterroles secrets-unsealer (rbac.authorization.k8s.io/v1)
INFO[0009] Garbage collecting rolebindings kube-system.sealed-secrets-controller (rbac.authorization.k8s.io/v1)
INFO[0010] Garbage collecting roles kube-system.sealed-secrets-key-admin (rbac.authorization.k8s.io/v1)
INFO[0011] Garbage collecting customresourcedefinitions functions.k8s.io (apiextensions.k8s.io/v1beta1)
INFO[0011] Garbage collecting customresourcedefinitions sealedsecrets.bitnami.com (apiextensions.k8s.io/v1beta1)
Error: the server could not find the requested resource (get functions.k8s.io)
Usage:
  kubeapps up FLAG [flags]

Flags:
      --dry-run   Provides output to be submitted to the server
  -h, --help      help for up

ERRO[0011] the server could not find the requested resource (get functions.k8s.io)

**Comment by anguslees** [comment]
Interesting.  It looks like it has removed the CRD definition before removing one of the Function objects.

So:
1. Fix dependency sorting to properly order CRD before/after other types
2. Treat resource-not-found as non-fatal when garbage collecting (it's really a variant of object-not-found)

@arapulido/@tuna to be _clear_ we understand what's going on here, it would be good to get the actual API call that is failing.  In kubecfg that would be "-v -v" - @tuna: do we have / can we add a similar "debug" level verbosity to kubeapps?

**Comment by anguslees** [comment]
Oh wait, what?  I couldn't work out why it was garbage collecting so many things at all - and I've just read the `up.go` code.  Atm, `up` breaks the update into two separate updates (namespaces separately), with garbage collection enabled on each.  That first namespace-only run garbage-collects everything (except the namespaces), since it thinks that's what the new state of the world should be.

So you're seeing all sorts of churn that shouldn't exist (and will delete all relevant server-side state, etc).

We need to put those back into a single invocation of the kubecfg ApplyCmd (or do other things differently).

**Comment by ngtuna** [comment]
I haven't had time to investigate this issue. Thanks Gus for clarifying this. I broke `up` into two separate updates because the installer needs to create mongodb secret object with the requirement that namespace `kubeapps` has been created before. Never thought `kubecfg` can detect the deployment dependency ordering. I am pushing it back to the manifest and test `up` again.

**Comment by ngtuna** [comment]
> do we have / can we add a similar "debug" level verbosity to kubeapps?

Yes I will add it

**Comment by arapulido** [comment]
Fixed
